### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape' 

### ISSUE THREAD

**Issue by ErikZhang-9762** [topazape/LSTM_Chem#13]
Hi，topazape
Thank you for developing such an excellent code.
I have some questions and I hope I can get your help.
When I run the command: Python train.py ，Attributeerror occurred，
I noticed that gwanseum had the same problem，borrow his pictures here.
![image](https://user-images.githubusercontent.com/51950798/101280346-945b4980-3803-11eb-9703-43ca01892245.png)
I didn't see your discussion with gwanseum,

I hope I can get your help！
Thanks in advance for your help,

Sincerely

**Comment by Mr-X9** [comment]
I used TF nightly GPU 2.5 instead of tensorflow 2.1
Is it possible to modify part of the code so that it can run.

**Comment by topazape** [comment]
I'm trying to reproduce this error. pls wait.

**Comment by JennyW5** [comment]
in data_loader.py, if update line 113  to  return self.X, self.y #, [None]
this problem is fixed

**Comment by pramodkp** [comment]
Hi，topazape

I am also getting the same error as Erik Zhang.
I am curious to know if it is solved.
Resuesting you to help in solving the error.

**Comment by topazape** [comment]
Hi, pramodkp

Okay, I'll try to check this. pls wait for a week.

**Comment by topazape** [comment]
Hi, @ErikZhang-9762 @pramodkp 

Thank you for your patience.
I have fixed the corresponding error and confirmed that it works.
The reason is that the return value of the data loader was invalid.
If you check it out, please let me know if you want to.

Thanks,

**Comment by pramodkp** [comment]
Thank you so much topazape for your quick help.
Now its works.

Thanks
