### ISSUE TITLE
Run on only 1 GPU, how to run on all the 4 available GPUs

### ISSUE THREAD

**Issue by pramodkp** [topazape/LSTM_Chem#19]
Model training and molecule generation run only on single GPU even if 4 GPUs are available.
How to run on all the GPUs available.

**Comment by topazape** [comment]
As you said, the Model only uses one GPU.
To be able to use multiple GPUs, it seems to use `tf.distribute.MirroredStrategy()`.
But I don't have a GPU, so I can't test it.
If you can run it on multiple GPUs, please PR it!
