### ISSUE TITLE
How I can get the file 'LSTM_Chem-22-0.42.hdf5'?

### ISSUE THREAD

**Issue by gwanseum** [topazape/LSTM_Chem#4]
Hello topazape,

Could you please share the file named' LSTM_Chem-22-0.42.hdf5'?

Thank you in advance!

**Comment by topazape** [comment]
@gwanseum 
Thank you for your request.
But I am sorry I can not share that `hdf5` file with two reasons.
1. The model is too big to share on GitHub. (GitHub prohibits sharing files over 100 MB)
2. The fine-tuned weight file `hdf5` is completely related to the target molecules. And target molecules include in-house data :(

So, please build the model yourself and prepare molecules (SMILES) for fine tuning yourself.

Thank you.

**Comment by gwanseum** [comment]
Hello, topazape,

I really appreciate your prompt response!

I got it ! but if it is possible, could you please let me know any references that I can refer to on how to generate fine-tuned weightfile hdf5.

Thank you  again.

Yours

**Comment by topazape** [comment]
@gwanseum 

OK, I will share a sample code. But unfortunately, this repo is old so I almost forgot the meaning of my code...😓 (Keras & TF upgrade is so fast and I use PyTorch now.)
Therefore, please wait a few days until pushing the sample code to this repo.

Sincerely,

**Comment by gwanseum** [comment]
@topazape 

I really appreciate that !

**Comment by topazape** [comment]
@gwanseum 

I am very sorry for the late reply.
I rewrote almost all the code using tf 2.0, wrote friendly `README.md`, and pushed the sample `*.ipynb`. I am very happy if this code becomes a holiday gift 😄 
Please See the master branch and try it!

Sincerely,

**Comment by gwanseum** [comment]
Hello, topazape,

Oh, WOW

Please note that I really really appreciate for your help and this code is
the most valuable christmas gift I have ever received so far!

Merry christmas!


Yours,

K.S SUH






2019년 12월 24일 (화) 오전 2:24, topazape <notifications@github.com>님이 작성:

**Comment by topazape** [comment]
@gwanseum 

I am happy that I can help you.
I will close this issue tonight, so if you have any questions, please add a new issue.

Merry Christmas!

Regards,

**Comment by gwanseum** [comment]
@topazape/LSTM_Chem
<reply@reply.github.com>

I got it.

I will

Thank you

Yours,

K.S SUH



2019년 12월 24일 (화) 오전 9:04, topazape <notifications@github.com>님이 작성:
