### ISSUE TITLE
Please update the dataset link to the one provided here!

### ISSUE THREAD

**Issue by ashishgupta1350** [topazape/LSTM_Chem#7]
http://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_26_sqlite.tar.gz

Source link : http://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/

**Comment by topazape** [comment]
Hi, @ashishgupta1350 

Thank you for the information.
I know that the ChEMBL DB has been upgraded, but I have no plans to rewrite the README for compatibility with the paper.

Sincerely,
