### ISSUE TITLE
Could you public the saved model for tranfer learning?

### ISSUE THREAD

**Issue by ashishgupta1350** [topazape/LSTM_Chem#8]
Hi, 
Really loved your work, I went through your code and through the paper, the code is well written and documented. 
I tried running the model and yes, it does take a lot of time to run on CPU, especially when I try to run on a mobile chip of a laptop. Unfortunately I don't have the luxury to get a GPU because of 2 reasons: 
1) The labs in our departments are closed due to quarentine for another 1.5 months
2) I don't have a pre - existing GPU to run CUDA .

If you could make your transfer learning model public ( Ie the trained model created from model.save() ) It would be a great help. I could then alter your code and use transfer learning for my usecase. 

1 solution I found was to use 100K data points to train the initial network ( LSTM Cell + RNN ) , however that is also quiet time consuming surprisingly on the CPU + the results will suffer. 

Awaiting your reply
Your's Sincerely

**Comment by topazape** [comment]
Hi, @ashishgupta1350 

Thanks for your comment.
As you mentioned, to fine-tune, you have to retrain from the model `./experiments/2020-03-24/LSTM_Chem/checkpoints/LSTM_Chem-22-0.45.hdf5`. (If you don't know how to retrain, look at `./example_Fine-tuning_for_TRPM8.ipynb`)Of course, the more GPU you have, the faster you can retrain.

So I would recommend using google colaboratory. You can use the GPU for free on it. However, I have not tested this repository to work properly on google colaboratory.

Sincerely,
